
remotes::install_github("vinecopulib/rvinecopulib@rotgumbel2")
remotes::install_github("tnagler/VineCopula@gumbel-sq")

library(ggplot2)
library(latex2exp)
library(ggridges)
library(stringr)
library(grid)
library(gridExtra)
library(cowplot)
library(tidyverse)
library(TDA)
library(nloptr)
library(VineCopula)
library(rvinecopulib)
library(latex2exp)
